"""Add school, requires_password_reset, and timestamp fields to User model

Revision ID: 26bd3593ef64
Revises: 6a514eb2dfd8
Create Date: 2025-11-23 00:36:31.307769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bd3593ef64'
down_revision = '6a514eb2dfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('requires_password_reset', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')
        batch_op.drop_column('requires_password_reset')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
