"""Make academic_session and semester NOT NULL

Revision ID: 6a514eb2dfd8
Revises: f9ec63633202
Create Date: 2025-11-22 04:17:10.940475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a514eb2dfd8'
down_revision = 'f9ec63633202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('academic_session',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('academic_session',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
