"""Force update models

Revision ID: c5dfe139b2a7
Revises: 26bd3593ef64
Create Date: 2025-11-25 04:38:40.704895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dfe139b2a7'
down_revision = '26bd3593ef64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index('idx_academic_session', ['academic_session'], unique=False)
        batch_op.create_index('idx_course_code', ['course_code'], unique=False)
        batch_op.create_index('idx_date_uploaded', ['date_uploaded'], unique=False)
        batch_op.create_index('idx_matric_no', ['matric_no'], unique=False)
        batch_op.create_index('idx_semester', ['semester'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_index('idx_semester')
        batch_op.drop_index('idx_matric_no')
        batch_op.drop_index('idx_date_uploaded')
        batch_op.drop_index('idx_course_code')
        batch_op.drop_index('idx_academic_session')

    # ### end Alembic commands ###
