"""Add academic_session and semester fields

Revision ID: f9ec63633202
Revises: 7c683ffb855b
Create Date: 2025-11-22 04:03:45.239390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ec63633202'
down_revision = '7c683ffb855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_session', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('academic_session')

    # ### end Alembic commands ###
